"""AI provider, extraction pipelines, metering.

Owns (single writer, BACKEND_DESIGN.md §5.1): extractions, ai_calls, ai_cost_rollups.
Other modules import only from this package root; only this module imports ``google.genai``.
"""

from __future__ import annotations

from eca.intelligence.budget import (
    DAILY_HARD_CAP_USD,
    DAILY_SOFT_CAP_USD,
    BudgetLevel,
    budget_level,
    daily_spend,
    level_for,
)
from eca.intelligence.config import AIConfig, build_ai_client, load_ai_config
from eca.intelligence.embedding import (
    EMBED_INPUT_VERSION,
    MAX_EMBED_BATCH,
    Embeddings,
    EmbeddingUnavailable,
    document_input,
    embed_documents,
    embed_query,
    embedding_model,
    input_digest,
    normalize,
    query_input,
    vector_literal,
)
from eca.intelligence.events import EXTRACTION_COMPLETED, ExtractionCompleted
from eca.intelligence.extraction import (
    ATTEMPT_CAP,
    EMAIL_PROMPT_VERSION,
    Candidate,
    Claim,
    EmailInput,
    ExtractionRecord,
    Participant,
    RunOutcome,
    claim,
    ensure_completed_event,
    get_extraction,
    latest_pending_for_source,
    mark_applied,
    mark_apply_failed,
    render_email_prompt,
    reset_apply,
    run_adjudication,
    run_email_extract,
    set_code_path,
    store_failure,
    store_success,
    succeeded_extractions,
)
from eca.intelligence.output_schemas import Adjudication, EmailExtraction, Statement, StatusSignal, Triage
from eca.intelligence.provenance import EvidenceSpan, Provenance, SourceRef, confidence_band
from eca.intelligence.provider.attempts import (
    Action,
    Decision,
    Degraded,
    ErrorKind,
    classify,
    next_background_attempt,
    run_interactive,
)
from eca.intelligence.provider.cassette import CassetteKey, CassetteStore, input_hash
from eca.intelligence.provider.client import AIClient, EmbedResult, GenerateResult
from eca.intelligence.provider.meter import CallRecord, Meter, bucket_floor, rollup_costs
from eca.intelligence.provider.pricing import PriceTable
from eca.intelligence.provider.registry import RoleRegistry, RoleSpec
from eca.intelligence.provider.types import (
    AIError,
    CallStatus,
    CassetteMiss,
    ConfigError,
    EmptyResponse,
    FileRef,
    NoFallback,
    PriceNotFound,
    ProviderError,
    ProviderRateLimited,
    ProviderRejected,
    ProviderTimeout,
    ProviderUnavailable,
    RoleDisabled,
    SafetyBlocked,
    SchemaInvalid,
    UnknownRole,
    Usage,
)
from eca.intelligence.purge import (
    AI_CALLS_RETENTION_DAYS,
    delete_extractions,
    extraction_ids_for_sources,
    purge_old_calls,
    purge_user,
)
from eca.intelligence.tasks import COST_ROLLUP_TASK, periodic_tasks

__all__ = [
    "AI_CALLS_RETENTION_DAYS",
    "ATTEMPT_CAP",
    "COST_ROLLUP_TASK",
    "DAILY_HARD_CAP_USD",
    "DAILY_SOFT_CAP_USD",
    "EMAIL_PROMPT_VERSION",
    "EMBED_INPUT_VERSION",
    "EXTRACTION_COMPLETED",
    "MAX_EMBED_BATCH",
    "AIClient",
    "AIConfig",
    "AIError",
    "Action",
    "Adjudication",
    "BudgetLevel",
    "CallRecord",
    "CallStatus",
    "Candidate",
    "CassetteKey",
    "CassetteMiss",
    "CassetteStore",
    "Claim",
    "ConfigError",
    "Decision",
    "Degraded",
    "EmailExtraction",
    "EmailInput",
    "EmbedResult",
    "EmbeddingUnavailable",
    "Embeddings",
    "EmptyResponse",
    "ErrorKind",
    "EvidenceSpan",
    "ExtractionCompleted",
    "ExtractionRecord",
    "FileRef",
    "GenerateResult",
    "Meter",
    "NoFallback",
    "Participant",
    "PriceNotFound",
    "PriceTable",
    "Provenance",
    "ProviderError",
    "ProviderRateLimited",
    "ProviderRejected",
    "ProviderTimeout",
    "ProviderUnavailable",
    "RoleDisabled",
    "RoleRegistry",
    "RoleSpec",
    "RunOutcome",
    "SafetyBlocked",
    "SchemaInvalid",
    "SourceRef",
    "Statement",
    "StatusSignal",
    "Triage",
    "UnknownRole",
    "Usage",
    "bucket_floor",
    "budget_level",
    "build_ai_client",
    "claim",
    "classify",
    "confidence_band",
    "daily_spend",
    "delete_extractions",
    "document_input",
    "embed_documents",
    "embed_query",
    "embedding_model",
    "ensure_completed_event",
    "extraction_ids_for_sources",
    "get_extraction",
    "input_digest",
    "input_hash",
    "latest_pending_for_source",
    "level_for",
    "load_ai_config",
    "mark_applied",
    "mark_apply_failed",
    "next_background_attempt",
    "normalize",
    "periodic_tasks",
    "purge_old_calls",
    "purge_user",
    "query_input",
    "render_email_prompt",
    "reset_apply",
    "rollup_costs",
    "run_adjudication",
    "run_email_extract",
    "run_interactive",
    "set_code_path",
    "store_failure",
    "store_success",
    "succeeded_extractions",
    "vector_literal",
]
