"""Context core: work items, decisions, evidence, context events, fold.

Owns (single writer, BACKEND_DESIGN.md §5.1): work_items, work_item_owners, decisions,
evidence, item_evidence, context_events, entity_links (Phase 2: thread continuation links).
Orchestrates email extraction and apply (§5.6). Other modules import only from this package root.
"""

from eca.work import pipeline as _pipeline  # registers the extract and apply handlers
from eca.work.actions import (
    DECISION_EDITABLE,
    LIFECYCLE_COMMANDS,
    create_item_for_user,
    decision_command,
    delete_user_item,
    edit_decision,
    edit_item,
    lifecycle_command,
    merge_items,
    verify_item,
)
from eca.work.apply import ApplyReport, apply_extraction
from eca.work.confidence import Confidence, band, compute
from eca.work.dates import DueResolution, compatible_due, resolve_due
from eca.work.events import ADJUDICATION_NEEDED, WORK_ITEM_CHANGED, AdjudicationNeeded, WorkItemChanged
from eca.work.fold import FoldEvent, FoldResult, fold
from eca.work.links import EntityLink, delete_links, link_entities, links_of
from eca.work.mapping import Mapped, authority, map_statement
from eca.work.pipeline import (
    APPLY_HANDLER,
    EXTRACT_HANDLER,
    ExtractionRetry,
    extract_source_item,
)
from eca.work.priority import (
    ItemPriorityInput,
    clear_closed_priority,
    priority_candidates,
    set_item_priority,
    set_item_priority_override,
)
from eca.work.purge import (
    REDACTED,
    delete_unreferenced_evidence,
    detach_conversations,
    purge_sources,
    purge_user,
    sources_still_referenced,
)
from eca.work.queries import (
    DecisionView,
    EvidenceView,
    Page,
    WorkItemDetail,
    evidence_of,
    get_decision,
    get_evidence,
    item_detail,
    list_decisions_page,
    list_items_page,
)
from eca.work.read import (
    HINT_MIN_SIMILARITY,
    HintSource,
    PersonWork,
    TimelineEvent,
    decisions_by_ids,
    decisions_created_between,
    decisions_for_conversations,
    decisions_for_hints,
    events_for,
    events_occurred_between,
    events_recorded_between,
    evidence_for,
    item_ids_for_sources,
    items_by_ids,
    items_for_project,
    open_items,
    person_work,
    project_hint_sources,
    search_decisions,
    search_items,
    source_item_stats,
    user_activity_since,
)
from eca.work.recompute import RecomputeReport, reapply_all, refold_all
from eca.work.service import (
    AppendResult,
    WorkItemView,
    add_note,
    append_event,
    assign_project,
    confirm,
    count_items,
    create_user_item,
    evidence_id_for,
    get_item,
    list_items,
    record_entity_event,
    reject,
    set_lifecycle,
    timeline,
    user_dedupe_key,
    user_edit,
)
from eca.work.time_sweep import TIME_SWEEP_TASK, SweepReport, periodic_tasks, sweep_all, sweep_user

del _pipeline

__all__ = [
    "ADJUDICATION_NEEDED",
    "APPLY_HANDLER",
    "DECISION_EDITABLE",
    "EXTRACT_HANDLER",
    "HINT_MIN_SIMILARITY",
    "LIFECYCLE_COMMANDS",
    "REDACTED",
    "TIME_SWEEP_TASK",
    "WORK_ITEM_CHANGED",
    "AdjudicationNeeded",
    "AppendResult",
    "ApplyReport",
    "Confidence",
    "DecisionView",
    "DueResolution",
    "EntityLink",
    "EvidenceView",
    "ExtractionRetry",
    "FoldEvent",
    "FoldResult",
    "HintSource",
    "ItemPriorityInput",
    "Mapped",
    "Page",
    "PersonWork",
    "RecomputeReport",
    "SweepReport",
    "TimelineEvent",
    "WorkItemChanged",
    "WorkItemDetail",
    "WorkItemView",
    "add_note",
    "append_event",
    "apply_extraction",
    "assign_project",
    "authority",
    "band",
    "clear_closed_priority",
    "compatible_due",
    "compute",
    "confirm",
    "count_items",
    "create_item_for_user",
    "create_user_item",
    "decision_command",
    "decisions_by_ids",
    "decisions_created_between",
    "decisions_for_conversations",
    "decisions_for_hints",
    "delete_links",
    "delete_unreferenced_evidence",
    "delete_user_item",
    "detach_conversations",
    "edit_decision",
    "edit_item",
    "events_for",
    "events_occurred_between",
    "events_recorded_between",
    "evidence_for",
    "evidence_id_for",
    "evidence_of",
    "extract_source_item",
    "fold",
    "get_decision",
    "get_evidence",
    "get_item",
    "item_detail",
    "item_ids_for_sources",
    "items_by_ids",
    "items_for_project",
    "lifecycle_command",
    "link_entities",
    "links_of",
    "list_decisions_page",
    "list_items",
    "list_items_page",
    "map_statement",
    "merge_items",
    "open_items",
    "periodic_tasks",
    "person_work",
    "priority_candidates",
    "project_hint_sources",
    "purge_sources",
    "purge_user",
    "reapply_all",
    "record_entity_event",
    "refold_all",
    "reject",
    "resolve_due",
    "search_decisions",
    "search_items",
    "set_item_priority",
    "set_item_priority_override",
    "set_lifecycle",
    "source_item_stats",
    "sources_still_referenced",
    "sweep_all",
    "sweep_user",
    "timeline",
    "user_activity_since",
    "user_dedupe_key",
    "user_edit",
    "verify_item",
]
