"""The ffmpeg path on synthetic media and AI-09/AI-10 through record-then-replay cassettes
(IMPLEMENTATION_PLAN.md §0.8 deferred pipeline tests).

Media are generated by ffmpeg from its built-in test sources (a colour pattern and a 440 Hz sine
tone): no real recording is used. The fake provider answers AI-09 and AI-10; a first run records
cassettes and a second run on a fresh database replays them with no provider at all, so the
replay path is exercised end to end. Requires ffmpeg and ffprobe (installed in CI).
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import uuid
from collections.abc import Iterator
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

import eca.meetings.pipeline as media_pipeline
from eca.intelligence.provider.types import GenerateRequest
from eca.meetings import media
from tests.api.support import ApiHarness, ApiUser, api_harness
from tests.conftest import TempDatabase, new_database

pytestmark = pytest.mark.db

DURATION_S = 4


def _require_ffmpeg() -> None:
    if shutil.which("ffmpeg") and shutil.which("ffprobe"):
        return
    if os.environ.get("CI"):
        pytest.fail("ffmpeg and ffprobe are required in CI")
    pytest.skip("ffmpeg/ffprobe not installed")


def _ffmpeg(*args: str) -> None:
    subprocess.run(["ffmpeg", "-nostdin", "-y", "-loglevel", "error", *args], check=True)


@pytest.fixture(scope="module")
def media_files(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    _require_ffmpeg()
    d = tmp_path_factory.mktemp("media")
    pattern = ["-f", "lavfi", "-i", f"testsrc=duration={DURATION_S}:size=96x64:rate=5"]
    tone = ["-f", "lavfi", "-i", f"sine=frequency=440:duration={DURATION_S}"]
    _ffmpeg(*pattern, *tone, "-shortest", "-c:v", "mpeg4", "-c:a", "aac", str(d / "video.mp4"))
    _ffmpeg(*pattern, "-c:v", "mpeg4", "-an", str(d / "silent.mp4"))
    _ffmpeg(*tone, "-c:a", "pcm_s16le", str(d / "tone.wav"))
    return {"video": d / "video.mp4", "silent": d / "silent.mp4", "tone": d / "tone.wav"}


def _upload(h: ApiHarness, user: ApiUser, data: bytes, mime: str, *, sha256: str | None = None) -> str:
    r = h.request(
        user,
        "POST",
        "/api/v1/recordings",
        json={
            "mime": mime,
            "bytes": len(data),
            "sha256": sha256 or hashlib.sha256(data).hexdigest(),
            "occurred_at": "2026-09-21T09:00:00+00:00",  # fixed: the AI-10 prompt carries the start
        },
        headers={"Idempotency-Key": f"m-{uuid.uuid4()}"},
    )
    assert r.status_code == 201, r.text
    upload = r.json()["upload"]
    assert h.client.put(upload["url"], content=data, headers=upload["headers"]).status_code == 201
    rec_id = str(r.json()["recording"]["id"])
    assert h.request(user, "POST", f"/api/v1/recordings/{rec_id}/complete").status_code == 202
    return rec_id


def _transcription(request: GenerateRequest) -> dict[str, Any]:
    return {
        "segments": [
            {"start_ms": 0, "end_ms": 1500, "speaker": "Speaker 1", "text": "Hello, this is Priya."},
            {
                "start_ms": 1600,
                "end_ms": 3900,
                "speaker": "Speaker 2",
                "text": "I will send the notes today.",
            },
        ],
        "complete": True,
    }


def _extraction(request: GenerateRequest) -> dict[str, Any]:
    return {
        "summary": "Short check-in.",
        "statements": [
            {
                "statement_kind": "promise",
                "action": "Send the notes",
                "speaker": "Speaker 2",
                "owner_ref": "speaker",
                "due_text": "today",
                "confidence": 0.9,
                "evidence": {"segment_seq": 1, "start_ms": 1600, "quote": "I will send the notes today"},
            }
        ],
    }


def _probe_json(path: Path) -> dict[str, Any]:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-print_format", "json", "-show_streams", str(path)],
        check=True,
        capture_output=True,
    ).stdout
    data: dict[str, Any] = json.loads(out)
    return data


def _state(h: ApiHarness) -> dict[str, Any]:
    return {
        "segments": h.rows(
            "SELECT seq, start_ms, end_ms, speaker_label, text FROM transcript_segments ORDER BY seq"
        ),
        "items": h.rows("SELECT title, direction, due_text FROM work_items ORDER BY title"),
        "status": h.rows("SELECT status, error_code FROM recordings"),
    }


@pytest.fixture
def h(isolated_db: TempDatabase, tmp_path: Path) -> Iterator[ApiHarness]:
    with api_harness(isolated_db, tmp_path) as harness:
        yield harness


def test_video_upload_is_reduced_to_audio_transcribed_and_replayed(
    h: ApiHarness, media_files: dict[str, Path], admin_base_url: str, tmp_path: Path
) -> None:
    cassettes = tmp_path / "recorded"
    h.ai_mode, h.cassette_dir = "record", cassettes
    h.fake_ai.responders["Transcription"] = _transcription
    h.fake_ai.responders["MeetingExtraction"] = _extraction
    user = h.user("avery@brightwater.example", "Avery Lindqvist")
    video = media_files["video"].read_bytes()
    rec_id = _upload(h, user, video, "video/mp4")
    h.drain()

    rec = h.request(user, "GET", f"/api/v1/recordings/{rec_id}").json()
    assert rec["status"] == "ready", rec
    assert rec["duration_s"] == pytest.approx(DURATION_S, abs=0.5)
    assert rec["transcription_model"] == "gemini-3.5-transcribe"
    # Only the prepared audio reached the provider: mono Opus, no video stream.
    assert [name for name, _ in h.fake_ai.uploads] == ["audio.ogg"]
    audio = next(h.objects.rglob("audio.ogg"))
    streams = _probe_json(audio)["streams"]
    # Opus always reports 48 kHz output; the 16 kHz resampling is in the fixed ffmpeg arguments.
    assert [(s["codec_type"], s["codec_name"], s["channels"]) for s in streams] == [("audio", "opus", 1)]
    assert h.fake_ai.deleted == [f"files/{h.fake_ai.uploads[0][1][:16]}"]  # deleted after success
    assert h.scalar("SELECT provider_file_ref FROM recordings") is None
    assert all(
        r.contents and r.contents[0].__class__.__name__ == "FileRef"
        for r in h.fake_ai.calls_for("Transcription")
    )
    recorded = _state(h)
    assert recorded["segments"] == [
        (0, 0, 1500, "Speaker 1", "Hello, this is Priya."),
        (1, 1600, 3900, "Speaker 2", "I will send the notes today."),
    ]
    assert recorded["items"] == [("Send the notes", "unresolved", "today")]
    roles = {p.relative_to(cassettes).parts[0] for p in cassettes.rglob("*.json")}
    assert {"meeting_extract", "transcribe"} <= roles, roles

    # Replay on a fresh database: the same upload gives the same transcript and items without a
    # provider (a cassette miss would raise and fail the drain).
    with new_database(admin_base_url, migrate=True) as db2, api_harness(db2, tmp_path / "replay") as h2:
        h2.ai_mode, h2.cassette_dir = "replay", cassettes
        user2 = h2.user("avery@brightwater.example", "Avery Lindqvist")
        rec2 = _upload(h2, user2, video, "video/mp4")
        h2.drain()
        assert h2.request(user2, "GET", f"/api/v1/recordings/{rec2}").json()["status"] == "ready"
        assert _state(h2) == recorded


def test_window_fallback_when_the_single_call_hits_the_output_limit(
    h: ApiHarness, media_files: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(media_pipeline, "WINDOW_S", 2)
    monkeypatch.setattr(media_pipeline, "window_starts", lambda d: media.window_starts(d, 2))
    calls: list[int] = []

    def transcribe(request: GenerateRequest) -> dict[str, Any]:
        calls.append(1)
        if len(calls) == 1:
            return {
                "segments": [{"start_ms": 0, "end_ms": 500, "speaker": "A", "text": "cut"}],
                "complete": False,
            }
        return {
            "segments": [
                {"start_ms": 500, "end_ms": 1500, "speaker": "Speaker 1", "text": f"window {len(calls) - 1}"}
            ]
        }

    h.fake_ai.responders["Transcription"] = transcribe
    user = h.user("avery@brightwater.example", "Avery Lindqvist")
    rec_id = _upload(h, user, media_files["tone"].read_bytes(), "audio/wav")
    h.drain()
    assert h.request(user, "GET", f"/api/v1/recordings/{rec_id}").json()["status"] == "ready"
    assert len(calls) == 3  # one truncated single call, then one call per 2-second window
    assert h.rows("SELECT start_ms, end_ms, speaker_label, text FROM transcript_segments ORDER BY seq") == [
        (500, 1500, "W1 Speaker 1", "window 1"),
        (2500, 3500, "W2 Speaker 1", "window 2"),
    ]
    assert len(h.fake_ai.uploads) == 3 and len(h.fake_ai.deleted) == 3  # every provider file deleted


@pytest.mark.parametrize(
    ("case", "code"),
    [("silent", "no_audio"), ("garbage", "unreadable"), ("checksum", "checksum_mismatch")],
)
def test_unusable_media_is_rejected_without_an_ai_call(
    h: ApiHarness, media_files: dict[str, Path], case: str, code: str
) -> None:
    user = h.user("avery@brightwater.example", "Avery Lindqvist")
    if case == "silent":
        rec_id = _upload(h, user, media_files["silent"].read_bytes(), "video/mp4")
    elif case == "garbage":
        rec_id = _upload(h, user, os.urandom(2048), "audio/mpeg")
    else:
        data = media_files["tone"].read_bytes()
        rec_id = _upload(h, user, data, "audio/wav", sha256=hashlib.sha256(b"declared").hexdigest())
    h.drain()
    rec = h.request(user, "GET", f"/api/v1/recordings/{rec_id}").json()
    assert (rec["status"], rec["error_code"]) == ("rejected", code)
    assert h.fake_ai.generate_calls == [] and h.fake_ai.uploads == []
    assert h.scalar("SELECT count(*) FROM transcript_segments") == 0


def test_duration_and_weekly_limits(
    h: ApiHarness, media_files: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    h.fake_ai.responders["Transcription"] = _transcription
    user = h.user("avery@brightwater.example", "Avery Lindqvist")
    tone = media_files["tone"].read_bytes()

    def limits(upload_h: float, weekly_h: float) -> None:
        cfg = SimpleNamespace(meetings=SimpleNamespace(max_upload_hours=upload_h, max_weekly_hours=weekly_h))
        monkeypatch.setattr(media_pipeline, "_budget_config", lambda: cfg)

    limits(1 / 3600, 10)  # 1 second per upload
    too_long = _upload(h, user, tone, "audio/wav")
    h.drain()
    assert h.request(user, "GET", f"/api/v1/recordings/{too_long}").json()["error_code"] == "duration_limit"

    limits(1, 6 / 3600)  # 6 seconds per week: the first 4-second tone fits, the second does not
    first = _upload(h, user, media_files["video"].read_bytes(), "video/mp4")
    h.drain()
    assert h.request(user, "GET", f"/api/v1/recordings/{first}").json()["status"] == "ready"
    second = _upload(h, user, tone + b"\x00" * 0, "audio/wav", sha256=None) if False else None
    assert second is None
    other = media_files["tone"].with_name("tone2.wav")
    _ffmpeg("-f", "lavfi", "-i", f"sine=frequency=660:duration={DURATION_S}", "-c:a", "pcm_s16le", str(other))
    over = _upload(h, user, other.read_bytes(), "audio/wav")
    h.drain()
    rec = h.request(user, "GET", f"/api/v1/recordings/{over}").json()
    assert (rec["status"], rec["error_code"]) == ("rejected", "weekly_limit")
