"""Tables owned by ``retrieval`` (BACKEND_DESIGN.md §5.1, §17.5). Mirrors migrations 0011, 0013 and 0026.

``embedding`` (``halfvec(768)``) is written only by the explicit SQL in ``indexing`` (which casts
the vector text) and read only as a distance in ``search``; ``tsv`` is generated by PostgreSQL.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import Column, DateTime, Integer, MetaData, Table, Text
from sqlalchemy.dialects.postgresql import ARRAY, BYTEA, JSONB, TSVECTOR
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import UserDefinedType


class HalfVec(UserDefinedType[Any]):
    """pgvector ``halfvec``: only used in distance expressions (``<=>``) in queries."""

    cache_ok = True

    def get_col_spec(self, **kw: Any) -> str:
        return "halfvec"


metadata = MetaData()
_U = PG_UUID(as_uuid=True)
_TS = DateTime(timezone=True)

chunks_table = Table(
    "chunks",
    metadata,
    Column("id", _U, primary_key=True),
    Column("user_id", _U, nullable=False),
    Column("source_item_id", _U, nullable=False),
    Column("chunk_index", Integer, nullable=False),
    Column("kind", Text, nullable=False),
    Column("title", Text),
    Column("text", Text, nullable=False),
    Column("token_count", Integer, nullable=False),
    Column("content_hash", BYTEA, nullable=False),
    Column("occurred_at", _TS, nullable=False),
    Column("conversation_id", _U),
    Column("meeting_id", _U),
    Column("person_ids", ARRAY(_U), nullable=False),
    Column("embedding", HalfVec()),
    Column("embedding_model", Text),
    Column("embedded_at", _TS),
    Column("start_ms", Integer),
    Column("end_ms", Integer),
    Column("tsv", TSVECTOR),
    Column("created_at", _TS),
    Column("updated_at", _TS),
)

retrieval_traces_table = Table(
    "retrieval_traces",
    metadata,
    Column("id", _U, primary_key=True),
    Column("user_id", _U, nullable=False),
    Column("query_hash", BYTEA, nullable=False),
    Column("surface", Text, nullable=False),
    Column("scenario", Text, nullable=False),
    Column("planner", Text, nullable=False),
    Column("plan", JSONB, nullable=False),
    Column("candidates", JSONB, nullable=False),
    Column("selected", JSONB, nullable=False),
    Column("coverage", JSONB, nullable=False),
    Column("context_tokens", Integer, nullable=False),
    Column("budget_tokens", Integer),
    Column("latency_ms", Integer, nullable=False),
    Column("created_at", _TS),
    implicit_returning=False,
)
