"""Meetings, participants, recordings and transcripts.

Owns (single writer, BACKEND_DESIGN.md §5.1): meetings, meeting_participants, recordings,
transcript_segments. Slice 1.6: meetings from calendar events. Phase 4: uploads (4.1), the media
pipeline and transcripts (4.2), speaker mapping and the meeting summary (4.3), prep storage (4.4).
Other modules import only from this package root.
"""

from eca.meetings import pipeline as _pipeline  # registers handlers
from eca.meetings import tasks as _tasks  # registers handlers
from eca.meetings.events import (
    MEETING_CHANGED,
    MEETING_PROCESSED,
    RECORDING_PREPARED,
    RECORDING_STAGE_DUE,
    RECORDING_UPLOADED,
    SPEAKER_MAPPING_CHANGED,
    TRANSCRIPT_STORED,
    MeetingChanged,
    MeetingProcessed,
    RecordingPrepared,
    RecordingStageDue,
    RecordingUploaded,
    SpeakerMappingChanged,
    TranscriptStored,
)
from eca.meetings.processing import (
    ExtractionStart,
    MeetingRecord,
    begin_extraction,
    defer_extract,
    deterministic_mapping,
    extract_failed,
    mark_processed,
    meeting_record,
    prior_meetings,
    record_ai_mappings,
    store_summary,
)
from eca.meetings.recordings import (
    MAX_MEDIA_BYTES,
    MAX_TRANSCRIPT_BYTES,
    MeetingSuggestion,
    RecordingView,
    UploadInit,
    classify_upload,
    complete_upload,
    delete_user_objects,
    get_recording,
    init_upload,
    link_meeting,
    list_recordings_page,
    meeting_suggestions,
    provider_file_refs,
    recording_for_meeting,
    recordings_by_source,
    retry_recording,
)
from eca.meetings.service import (
    MeetingDetail,
    MeetingView,
    cancel_from_deleted_source,
    get_meeting_details,
    meeting_details_between,
    meeting_ids_for_sources,
    meetings_between,
    meetings_by_sources,
    purge_sources,
    purge_user,
    upcoming_attendee_ids,
    upsert_from_source,
)
from eca.meetings.speakers import (
    AUTO_APPLY,
    Proposal,
    SpeakerMapping,
    applied_labels,
    set_speaker_mapping,
    speaker_mappings,
    transcript_labels,
)
from eca.meetings.tasks import MEDIA_SWEEP_TASK, periodic_tasks
from eca.meetings.transcripts import Segment, TranscriptView, current_transcript, load_segments

del _pipeline, _tasks

__all__ = [
    "AUTO_APPLY",
    "MAX_MEDIA_BYTES",
    "MAX_TRANSCRIPT_BYTES",
    "MEDIA_SWEEP_TASK",
    "MEETING_CHANGED",
    "MEETING_PROCESSED",
    "RECORDING_PREPARED",
    "RECORDING_STAGE_DUE",
    "RECORDING_UPLOADED",
    "SPEAKER_MAPPING_CHANGED",
    "TRANSCRIPT_STORED",
    "ExtractionStart",
    "MeetingChanged",
    "MeetingDetail",
    "MeetingProcessed",
    "MeetingRecord",
    "MeetingSuggestion",
    "MeetingView",
    "Proposal",
    "RecordingPrepared",
    "RecordingStageDue",
    "RecordingUploaded",
    "RecordingView",
    "Segment",
    "SpeakerMapping",
    "SpeakerMappingChanged",
    "TranscriptStored",
    "TranscriptView",
    "UploadInit",
    "applied_labels",
    "begin_extraction",
    "cancel_from_deleted_source",
    "classify_upload",
    "complete_upload",
    "current_transcript",
    "defer_extract",
    "delete_user_objects",
    "deterministic_mapping",
    "extract_failed",
    "get_meeting_details",
    "get_recording",
    "init_upload",
    "link_meeting",
    "list_recordings_page",
    "load_segments",
    "mark_processed",
    "meeting_details_between",
    "meeting_ids_for_sources",
    "meeting_record",
    "meeting_suggestions",
    "meetings_between",
    "meetings_by_sources",
    "periodic_tasks",
    "prior_meetings",
    "provider_file_refs",
    "purge_sources",
    "purge_user",
    "record_ai_mappings",
    "recording_for_meeting",
    "recordings_by_source",
    "retry_recording",
    "set_speaker_mapping",
    "speaker_mappings",
    "store_summary",
    "transcript_labels",
    "upcoming_attendee_ids",
    "upsert_from_source",
]
